version: '3.8'

services:
  app:
    build: .
    container_name: main-service
    ports:
      - '3000:3000'
    depends_on:
      - users-service
      - school-service
      - district-service
      - report-service 
    networks:
      - hubescolar-network
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    env_file:
      - .env

  users-service:
    build: ./services/users-service
    container_name: users-service
    ports:
      - '3001:3001'
    networks:
      - hubescolar-network
    volumes:
      - ./services/users-service/logs:/app/logs
    restart: unless-stopped
    env_file:
      - ./services/users-service/.env

  auth-service:
    build: ./services/auth-service
    container_name: auth-service
    ports:
      - '3004:3004'
    networks:
      - hubescolar-network
    volumes:
      - ./services/auth-service/logs:/app/logs
    restart: unless-stopped
    env_file:
      - ./services/auth-service/.env
    depends_on:
      - users-service

  school-service:
    build: ./services/school-service
    container_name: school-service
    ports:
      - '3002:3002'
    networks:
      - hubescolar-network
    volumes:
      - ./services/school-service/logs:/app/logs
    restart: unless-stopped
    env_file:
      - ./services/school-service/.env
    depends_on:
      - mysql

  district-service:
    build: ./services/district-service
    container_name: district-service
    ports:
      - '3003:3003'
    networks:
      - hubescolar-network
    volumes:
      - ./services/district-service/logs:/app/logs
    restart: unless-stopped
    env_file:
      - ./services/district-service/.env
    depends_on:
      - mysql

  report-service:
    build: ./services/report-service
    container_name: report-service
    ports:
      - '3005:3005'
    networks:
      - hubescolar-network
    volumes:
      - ./services/report-service/logs:/app/logs 
    restart: unless-stopped
    env_file:
      - ./services/report-service/.env
    depends_on:
      - users-service

  mysql:
    image: mysql:8.0
    container_name: mysql-hubescolar
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - hubescolar-network
    restart: unless-stopped
    env_file:
      - ./mysql/.env

networks:
  hubescolar-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local